# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatglm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rchatglm.proto\"\x1c\n\x0cGreetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\'\n\x0b\x43hatHistory\x12\x18\n\x05turns\x18\x01 \x03(\x0b\x32\t.ChatTurn\"\x1b\n\x08\x43hatTurn\x12\x0f\n\x07strings\x18\x01 \x03(\t\"*\n\x10GenerateResponse\x12\x16\n\x0egenerated_text\x18\x01 \x01(\t\"l\n\x0fGenerateRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x11\n\tdo_sample\x18\x02 \x01(\x08\x12\x12\n\nmax_length\x18\x03 \x01(\x05\x12\x13\n\x0btemperature\x18\x04 \x01(\x02\x12\r\n\x05top_p\x18\x05 \x01(\x02\"I\n\x0c\x43hatResponse\x12\x16\n\x0egenerated_text\x18\x01 \x01(\t\x12!\n\x0bnew_history\x18\x02 \x01(\x0b\x32\x0c.ChatHistory\"\x86\x01\n\x0b\x43hatRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x1d\n\x07history\x18\x02 \x01(\x0b\x32\x0c.ChatHistory\x12\x11\n\tdo_sample\x18\x03 \x01(\x08\x12\x12\n\nmax_length\x18\x04 \x01(\x05\x12\x13\n\x0btemperature\x18\x05 \x01(\x02\x12\r\n\x05top_p\x18\x06 \x01(\x02\x32\xd7\x01\n\x0b\x43hatGLM2RPC\x12+\n\x05Greet\x12\r.GreetRequest\x1a\x11.GenerateResponse\"\x00\x12\x31\n\x08Generate\x12\x10.GenerateRequest\x1a\x11.GenerateResponse\"\x00\x12\x39\n\x0eStreamGenerate\x12\x10.GenerateRequest\x1a\x11.GenerateResponse\"\x00\x30\x01\x12-\n\nStreamChat\x12\x0c.ChatRequest\x1a\r.ChatResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatglm_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GREETREQUEST']._serialized_start=17
  _globals['_GREETREQUEST']._serialized_end=45
  _globals['_CHATHISTORY']._serialized_start=47
  _globals['_CHATHISTORY']._serialized_end=86
  _globals['_CHATTURN']._serialized_start=88
  _globals['_CHATTURN']._serialized_end=115
  _globals['_GENERATERESPONSE']._serialized_start=117
  _globals['_GENERATERESPONSE']._serialized_end=159
  _globals['_GENERATEREQUEST']._serialized_start=161
  _globals['_GENERATEREQUEST']._serialized_end=269
  _globals['_CHATRESPONSE']._serialized_start=271
  _globals['_CHATRESPONSE']._serialized_end=344
  _globals['_CHATREQUEST']._serialized_start=347
  _globals['_CHATREQUEST']._serialized_end=481
  _globals['_CHATGLM2RPC']._serialized_start=484
  _globals['_CHATGLM2RPC']._serialized_end=699
# @@protoc_insertion_point(module_scope)
